#
# Copyright 2025 Miklos Vajna
#
# SPDX-License-Identifier: MIT
#

[book]
title = "turtle-cpm user guide"

[output.html]
edit-url-template = "https://github.com/vmiklos/turtle-cpm/edit/main/guide/{path}"
additional-js = ["matomo.js"]
